version: '3'
services:
  odoo:
    container_name: odoo-erp-onprem
    image: odoo:latest
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "127.0.0.1:8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo:/etc/odoo
  postgres:
    container_name: postgresql
    image: postgres:latest
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:80"
  celonis-extractor:
    container_name: celonis-jdbc-onprem-extractor
    image: connector-jdbc-on-prem:2.103.0
    env_file: uplink.env
    environment:
      - UPLINK_ENABLED=true

volumes:
  data:
  db:
